name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: "C:\\ProgramData\\scoop\\apps\\llvm\\current\\bin"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install LLVM
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop install llvm --global

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dev-build
        path: target/debug/rblx_rich_presence.exe